# https://ngc.nvidia.com/catalog/containers/nvidia:tensorrtserver/tags
# 

# Before 19.07, pytorch models are not supported
# ref: https://github.com/NVIDIA/tensorrt-inference-server/releases

# <Release 1.4.0, corresponding to NGC container 19.07>
# Added libtorch as a new backend. PyTorch models manually decorated or automatically 
# traced to produce TorchScript can now be run directly by the inference server.

# FROM nvcr.io/nvidia/tensorrtserver:19.03-py3
# FROM nvcr.io/nvidia/tensorrtserver:20.01-py3
# FROM nvcr.io/nvidia/tensorrtserver:20.01-py3
FROM nvcr.io/nvidia/tensorrtserver:20.03-py3






